/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa2021.f1;

import it.unicam.cs.pa2021.f1.controller.TrackFileReader;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) {
        TrackFileReader tcr = new TrackFileReader();

    }
}
