/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa2021.f1;

import it.unicam.cs.pa2021.f1.view.ConsoleView;

public class App {

    public static void main(String[] args) {

        ConsoleView consoleView = new ConsoleView();
        consoleView.open();

        /*
         //Application.launch(args);
         RacingPlanReader tcr = new RacingPlanReader();
         int i = 0;

         DefaultRacingPlan racingPlan = null;
         DefaultGameEngine engine = new DefaultGameEngine(racingPlan);

         DefaultRacingVehicle rv = new DefaultRacingVehicle();
         DefaultRacingVehicle rc = new DefaultRacingVehicle();
         DefaultRacingVehicle rs = new DefaultRacingVehicle();
         DefaultPilot bot = new DefaultPilot("bot", rv, PilotType.BOT);
         DefaultPilot bob = new DefaultPilot("bob", rc, PilotType.BOT);
         DefaultPilot bor = new DefaultPilot("bor", rs, PilotType.BOT);
         BotController botController = new BotController(racingPlan);
         //racingPlan.printRacingPlanConsole();


         while (rv.getPosition().getY() + 1 < racingPlan.getHeight()  && rc.getPosition().getY() + 1  < racingPlan.getHeight() &&
         rs.getPosition().getY() + 1  < racingPlan.getHeight() ) {
         System.out.println("\n");
         botController.botNextPosition(bot.getRacingVehicle());
         System.out.println(bot.getRacingVehicle().getPosition().toString());
         botController.botNextPosition(bob.getRacingVehicle());
         System.out.println(bob.getRacingVehicle().getPosition().toString());
         botController.botNextPosition(bor.getRacingVehicle());
         System.out.println(bor.getRacingVehicle().getPosition().toString());
         //racingPlan.printRacingPlanConsole();
         i++;
         }
         */
    }

    public String getGreeting() {
        return "Hello World!";
    }
}
