/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa2021.f1;


import org.junit.jupiter.api.Test;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {

    }
}
